### PR TITLE
New activate

### PR DESCRIPTION
**Pull request by yonicd**

### CODE REVIEW

**Comment by jonthegeek** [comment]
You should delete the commented code. That's what version control is for!

**Comment by yonicd** [comment]
Ha. indeed. I was debating with myself to add deprecated calls to those functions

**Review by jonthegeek — APPROVED** [review]
Optionally remove the commented code, otherwise this looks great!

**Comment by yonicd** [comment]
i'll keep the comment code for this merge and remove it for the next update when vignettes are sorted out

**Pull request merged**
