### PR TITLE
Return token invisibly from add_team_code

### PR DESCRIPTION
**Pull request by jonthegeek**
No tests 'cuz tests are broken and I'm not sure I understand the structure anyway. SUPER small change, though. Tested by using it in mentordash.

### CODE REVIEW

**Comment by jonthegeek** [comment]
Ok, not needed, it's better for me to grab this after the team is activated.

**Comment by jonthegeek** [comment]
I need this after all.

**Comment by jonthegeek** [comment]
Getting this fully functional before I request that you review.

**Comment by yonicd** [comment]
please synch with upstream. these tests should be passing when synched with master

**Comment by jonthegeek** [comment]
Theoretically this is updated.

**Comment by jonthegeek** [comment]
No need for this PR anymore. To be clear, I realllly need the feature in order to un-break mentordash (it currently kinda sorta works but is super slow and bad), but I don't need this PR.

**Comment by yonicd** [comment]
this pr https://github.com/yonicd/slackteams/pull/26/ will fix your issue

https://github.com/yonicd/slackteams/pull/26/files#diff-7ef534a535df761032d5470122fb9d2eR123

**Pull request closed without merging**
