### PR TITLE
Issue 12 httr

### LINKED ISSUE #11: Add Team Interactively
As a user, I'd like to load a team interactively with an httr browser launch, so that I don't have to work too hard to get this set up.

This should always load the team into the `.slack` environment, but also (optionally) save a cached version for future loading.

Make sure that no downstream functions *require* the file (change them if they do).

### LINKED ISSUE #12: Add Team via Token
As a shiny app, I'd like to add (and/or activate) a team using just a token, or maybe token + team name (although that's in the httr token, so, if we require that rather than just the string, the httr token will be enough).

This can be used by #11, but is also needed on its own (because the shiny app will handle the calls to generate the token).

### PR DESCRIPTION
**Pull request by jonthegeek**
This isn't perfect, but it's pretty darned useful.

We should decide if we want to change the slackteams API (as in the order of commands in the functions, names of core functions, etc) now, I think; it's still very alpha, so I think it's ok, but the clock is ticking.

All that said... I'm hoping to hide the API from users somewhat via the r4ds package, so it may not matter for my particular use case.

Closes #12.
Closes #11.

### CODE REVIEW

**Comment by yonicd** [comment]
what changes did you have in mind?

**Comment by jonthegeek** [comment]
I guess mostly... do we want to continue also supporting the other method of doing things, or just switch to all oauth2? At the moment it's fine to have both, but maybe not forever?

I don't have a strong reason to REMOVE that functionality, so I think it's probably fine to leave everything as is. But it's worth sorting out sooner rather than later.

**Comment by yonicd** [comment]
For now i think it is ok to keep. The package is a bridge to {slackr} users (there a lot of them) which is why i put in dcf orginally, i just haven’t publicized it while the idea is maturing.

We can highlight oauth2 over the other methods for sure. the current method will be grandfathered over time, seeing that all the tokens that heroku made will work fine too.

**Comment by jonthegeek** [comment]
To-do:

- [x] Better default scopes.
- [x] Consider implementing roles (do we do that here/now, or worry about that later?). Probably save scopes allowed by the token as part of the token (right now we only save a tiny fraction of the full token object, since all we really *need* is the token itself).
- [x] Consider implementing ~places (local, shinyapps.io, server). Need to think about what `redirect_uri`s we want to allow to do this. Only ones we pre-configure are possible.
- [ ] TESTS.

**Comment by yonicd** [comment]
does `add_team_token` need to be exported?

**Comment by jonthegeek** [comment]
> does `add_team_token` need to be exported?

It should be. It'll be used for the mentordash login.

**Pull request merged**
