### PR TITLE
Export get_conversations_list

### PR DESCRIPTION
**Pull request by jonthegeek**
Relatively straightforward. Please double-check that the help fits your style.

### CODE REVIEW

**Comment by jonthegeek** [comment]
Closes #27.

**Comment by jonthegeek** [comment]
There's a 404 in the GHA. It appears to be unrelated to my change.

One of the tests fails locally, specifically the one looking at `res_convo_list$id` on line 31 of `test-02_api_calls.R`. I think we have different private channel IDs, probably?

**Review by yonicd — APPROVED** [review]

**Comment by yonicd** [comment]
Looks good. Seems to be a problem with the ci install of r4.0.3

**Comment by yonicd** [comment]
can you synch master into this branch. i fixed the tests (016025e) and they should pass now on all PRs.

thanks

**Pull request closed without merging**
